Repository andela/selene-ah-backend, pull requests merged in 2019-01, with the labels that each got.

#82 #161779872 Implement notification system
  .env.sample
  .eslintignore
  package-lock.json
  package.json
  server/config/notification.js
  server/controllers/NotificationController.js
  server/controllers/articlesController.js
  server/controllers/commentController.js
  server/controllers/followersController.js
  server/helpers/articleHelper.js
  server/helpers/notificationHelper.js
  server/migrations/20181204145930-create-notification.js
  server/models/notification.js
  server/services/pusher.js
  tests/controllers/notification.test.js
  tests/models/notification.test.js
Labels: needs review

#86 #161779884 users are able to add highlighted comments to articles
  server/controllers/articlesController.js
  server/controllers/highlightedComment.js
  server/middlewares/validations/uuidValidator.js
  server/migrations/20181222150605-create-highlighted-comment.js
  server/migrations/20181222152635-create-user-highlighted-comment.js
  server/models/article.js
  server/models/highlightedcomment.js
  server/models/user.js
  server/models/userhighlightedcomment.js
  server/routes/api/articlesRoute.js
  tests/articles/highlightedComment.test.js
  tests/articles/reportArticle.test.js
  tests/models/article.test.js
  tests/models/user.test.js
Labels: needs review

#83 #161779873 Implement CRUD functionalities for article tag
  package-lock.json
  package.json
  server/controllers/articleTagsController.js
  server/controllers/articlesController.js
  server/helpers/calculateArticleReadTime.js
  server/helpers/checkIfUserOwnsTheArticle.js
  server/helpers/findOrCreateTag.js
  server/helpers/getTag.js
  server/middlewares/validations/checkIfArticleIsOwnedByUser.js
  server/middlewares/validations/uuidValidator.js
  server/models/article.js
  server/models/articleTag.js
  server/models/tag.js
  server/routes/api/articleTagRoute.js
  server/routes/api/articlesRoute.js
  server/routes/index.js
  tests/articles/articles.test.js
  tests/helpers/sendEmail.test.js
  tests/models/articleTag.test.js
Labels: ready

#84 #161779881 Implement user comment reaction functionality
  README.md
  server/controllers/CommentReactionController.js
  server/controllers/commentController.js
  server/docs/commentReaction.yaml
  server/docs/config/swaggerConfig.js
  server/helpers/LikesCount.js
  server/helpers/responseMessages.js
  server/middlewares/validations/ReactionValidation.js
  server/middlewares/validations/uuidValidator.js
  server/migrations/20181226194636-create-comment-reaction.js
  server/models/comment.js
  server/models/commentLikes.js
  server/models/commentReaction.js
  server/models/user.js
  server/routes/api/commentReaction.js
  server/routes/index.js
  tests/comments/commentReaction.test.js
  tests/models/commentReaction.js
Labels: needs review

#85 #161779885 Create comment history for every updated comment
  server/controllers/commentController.js
  server/middlewares/validations/commentValidation.js
  server/middlewares/validations/uuidValidator.js
  server/migrations/20181203143538-create-comment-history.js
  server/models/comment.js
  server/models/commentHistory.js
  server/models/user.js
  server/routes/api/commentRoute.js
  tests/comments/comment.test.js
Labels: needs review

#91 fix(bug fix): fix bug in validation helpers
  package-lock.json
  server/helpers/validation/validations.js
  server/middlewares/validations/passwordValidation.js
  server/routes/api/v1/auth/userAuthRoute.js
  tests/comments/comment.test.js
  tests/users/password.test.js
  tests/users/signIn.test.js
  tests/users/signUp.test.js
Labels: needs review, ready

#98 fix(bug fix): fix vote controller
  server/controllers/article/articlesController.js
  server/controllers/votes/VoteController.js
  server/middlewares/validations/articleVoteValidator.js
  server/models/article.js
  server/models/index.js
  tests/controllers/votes/voteController.test.js
Labels: needs review, ready

#105 fix-user-stats
  package-lock.json
  server/controllers/article/articlesController.js
  server/controllers/bookmark/bookmarkController.js
  server/controllers/comment/commentController.js
  server/controllers/user/followersController.js
  server/controllers/votes/VoteController.js
  server/middlewares/JWTAuthentication.js
  server/middlewares/validations/articleValidation.js
  server/routes/api/v1/articlesRoute.js
  server/routes/api/v1/bookmarkRoute.js
  server/routes/api/v1/commentRoute.js
  server/routes/api/v1/voteRoute.js
  tests/articles/articleStat.test.js
  tests/comments/comment.test.js
  tests/controllers/bookmarkController.test.js
  tests/controllers/votes/voteController.test.js
  tests/follower/getFollowers.test.js
Labels: ready
